### ISSUE TITLE
Memory allocation fails for queries and scans when index is missing

### ISSUE THREAD

**Issue by jonas32** [aerospike/aerospike-client-rust#75]
This issue targets the `as_eq` filter.
When a `as_eq` filter is created with a string value, but the bin does not have a string type Secondary Index, it can fail memory allocation. It does not fail, if the filter is any other than `as_eq` or the bin has an Index. Also integer values are safe. Even with perfect conditions for this error, it seems not to fail everytime.
This is a hard to reproduce bug. For more about it, see [this comment](https://github.com/aerospike/aerospike-client-rust/pull/71#issuecomment-657170051) 

// Update
I just found out, that also Numeric Queries on a String type Index bin can cause this to happen. Seems to be even more reproduceable.

**Comment by jhecking** [comment]
@jonas32 Thanks for catching this issue and doing the initial debugging! Based on your observations, I was able to reproduce the problem, and with a little more debugging, find the root cause.

The trick to reproduce the issue is to cause any kind of server error in a query command, and then have that same connection reused to send any other kind of command. When the query command returns a server error other than `KeyNotFoundError`, the connection buffer is not cleared, and the next command reusing the same network connection will attempt to parse the remaining bytes in the buffer as a server response. That often leads to a situation where some bytes are interpreted as the message size, which can trigger this bail out in the `Buffer::resize_buffer` method:

```
        // Corrupted data streams can result in a huge length.
        // Do a sanity check here.
        if size > MAX_BUFFER_SIZE {
            bail!("Invalid size for buffer: {}", size);
        }
```

Or, if the next command reusing the connection is an info command, it would lead to the info command buffer getting resized, which is just a regular `Vec<u8>` and has no similar protections.
